---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: grafana-release
- name: version

outputs:
- name: rc

run: {path: grafana-release/ci/tasks/create-rc}
