---
platform: linux

inputs:
  - name: grafana-boshrelease
  - name: grafana-binary-version

outputs:
  - name: grafana-boshrelease

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: grafana-boshrelease/ci/tasks/update-grafana-blob.sh
